### ISSUE TITLE
Where is the schema-registry-ui's `values.yaml` file?

### ISSUE THREAD

**Issue by hongbo-miao** [ricardo-aires/helm-charts#12]
I can install schema-registry-ui by

```shell
helm upgrade \
  schema-registry-ui \
  schema-registry-ui \
  --install \
  --repo=https://ricardo-aires.github.io/helm-charts
```

However, I cannot find its values.yaml file in this repo.

Where can I find it? Thanks! 😃

**Comment by ricardo-aires** [comment]
At this time I'm not maintaining the `schema-registry-ui`, if a released of the  chart is installed the values can be get using the [helm get values command](https://helm.sh/docs/helm/helm_get_values/):

```bash
$ # get overwritten values
$ helm get values RELEASE_NAME
$ # get all values
$ helm get values RELEASE_NAME --all
```

Another options is to use the [helm pull]( [installed](https://helm.sh/docs/helm/helm_pull/)) command to download the archive, or download it from [schema-registry-ui-0.1.0.tgz](https://github.com/ricardo-aires/helm-charts/blob/main/schema-registry-ui-0.1.0.tgz).

**Comment by hongbo-miao** [comment]
Thanks @ricardo-aires ! As [schema-registry-ui](https://github.com/lensesio/schema-registry-ui) hasn't updated for two years.

I just found another better open source option [Redpanda Console](https://github.com/redpanda-data/console) which works great with Confluent Registry:

<img width="1608" alt="image" src="https://user-images.githubusercontent.com/3375461/236664501-93aad87e-381d-40a2-8f3a-b9682886ca40.png">

I will close this for now, thank again! 😃
